#version: '3.8'
#
#networks:
#
#  spring-network:
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql_container
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: gestionconge
#    ports:
#      - "3307:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-proot"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - spring-network
#
#  server_app:
#    build:
#      context: .
#    container_name: server_app
#    ports:
#      - "9090:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/gestionconge?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
#    networks:
#      - spring-network
#    restart: on-failure
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: phpmyadmin
#    environment:
#      PMA_HOST: mysql_container
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "8080:80"
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - spring-network
