# ## Utilisez une image Java de base
# #FROM openjdk:17
# #ADD target/server.jar server.jar
# #
# ##ARG JAR_FILE="/target/*.jar"
# ### Copiez le jar de votre application dans le conteneur
# ##COPY ${JAR_FILE} /app/Server.jar
# #
# ## Définissez le répertoire de travail
# ##WORKDIR /app
# #
# ## Commande pour exécuter l'application Spring Boot lorsque le conteneur démarre
# #ENTRYPOINT ["java", "-jar", "Server.jar"]
#
#
# # Utiliser l'image OpenJDK
# FROM openjdk:17-jdk-alpine
#
# # Argument pour le fichier JAR
# ARG JAR_FILE=target/Server-0.0.1-SNAPSHOT.jar
#
# # Copier le fichier JAR dans le conteneur
# COPY ${JAR_FILE} app.jar
#
# # Commande pour exécuter l'application
# ENTRYPOINT ["java","-jar","/app.jar"]